import { SketchElement } from "@repo/canvas-core/types";

export const SYSTEM_TEMPLATES: {
  name: string;
  description: string;
  elements: SketchElement[];
  thumbnail?: string;
}[] = [
  {
    name: "Blank",
    description: "A clean slate for your ideas.",
    elements: [],
  },
  {
    name: "Cornell Notes",
    description: "Structured layout for effective note-taking.",
    elements: [
      {
        id: "cornell-title-rect",
        tool: "rectangle",
        x1: 50,
        y1: 50,
        x2: 750,
        y2: 120,
        seed: 123,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 2,
        text: "Title / Topic",
      },
      {
        id: "cornell-cue-rect",
        tool: "rectangle",
        x1: 50,
        y1: 130,
        x2: 250,
        y2: 600,
        seed: 456,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 2,
        text: "Cues / Questions",
      },
      {
        id: "cornell-notes-rect",
        tool: "rectangle",
        x1: 260,
        y1: 130,
        x2: 750,
        y2: 600,
        seed: 789,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 2,
        text: "Notes",
      },
      {
        id: "cornell-summary-rect",
        tool: "rectangle",
        x1: 50,
        y1: 610,
        x2: 750,
        y2: 750,
        seed: 321,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 2,
        text: "Summary",
      },
    ],
  },
  {
    name: "Comparison Table",
    description: "Compare and contrast two concepts.",
    elements: [
      {
        id: "comp-header",
        tool: "rectangle",
        x1: 50,
        y1: 50,
        x2: 750,
        y2: 110,
        seed: 111,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 2,
      },
      {
        id: "comp-divider-vertical",
        tool: "line",
        x1: 400,
        y1: 50,
        x2: 400,
        y2: 600,
        seed: 222,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 2,
      },
      {
        id: "comp-divider-horizontal",
        tool: "line",
        x1: 50,
        y1: 110,
        x2: 750,
        y2: 110,
        seed: 333,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 2,
      },
      {
        id: "comp-text-1",
        tool: "text",
        x1: 150,
        y1: 70,
        x2: 300,
        y2: 90,
        seed: 444,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 1,
        text: "Option A",
      },
      {
        id: "comp-text-2",
        tool: "text",
        x1: 550,
        y1: 70,
        x2: 700,
        y2: 90,
        seed: 555,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 1,
        text: "Option B",
      },
    ],
  },
  {
    name: "Flowchart",
    description: "Map out processes and logic.",
    elements: [
      {
        id: "flow-start",
        tool: "ellipse",
        x1: 350,
        y1: 50,
        x2: 450,
        y2: 110,
        seed: 666,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 2,
        text: "Start",
      },
      {
        id: "flow-arrow-1",
        tool: "line",
        x1: 400,
        y1: 110,
        x2: 400,
        y2: 180,
        seed: 777,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 2,
      },
    ],
  },
  {
    name: "Problem Solving",
    description: "Template for algorithmic challenges.",
    elements: [
      {
        id: "prob-statement",
        tool: "rectangle",
        x1: 50,
        y1: 50,
        x2: 750,
        y2: 150,
        seed: 888,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 2,
        text: "Problem Statement",
      },
      {
        id: "prob-approach",
        tool: "rectangle",
        x1: 50,
        y1: 160,
        x2: 750,
        y2: 300,
        seed: 999,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 2,
        text: "Approach",
      },
      {
        id: "prob-pseudo",
        tool: "rectangle",
        x1: 50,
        y1: 310,
        x2: 750,
        y2: 600,
        seed: 101,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 2,
        text: "Pseudocode",
      },
      {
        id: "prob-complexity",
        tool: "rectangle",
        x1: 50,
        y1: 610,
        x2: 750,
        y2: 700,
        seed: 202,
        strokeColor: "#000000",
        fillColor: "none",
        fillStyle: "none",
        strokeWidth: 2,
        text: "Complexity (Time/Space)",
      },
    ],
  },
];
